// Ansible vars_file containing variable values from Terraform.
// Generated by Terraform mgmt configuration.

// hosts public dns - for building project
env.jenkins_user="ubuntu@ec2-3-11-232-111.eu-west-2.compute.amazonaws.com"
env.testvm_user="ubuntu@ec2-18-130-213-34.eu-west-2.compute.amazonaws.com"
env.K8S_CLuster_user="ubuntu@ec2-35-178-24-55.eu-west-2.compute.amazonaws.com"

// host key generated for ssh into vms
env.EC2_private_key="AWS_EU_Key"
