// Ansible vars_file containing variable values from Terraform.
// Generated by Terraform mgmt configuration.

// hosts public dns - for building project
env.jenkins_user="ubuntu@ec2-3-10-90-233.eu-west-2.compute.amazonaws.com"
env.testvm_user="ubuntu@ec2-18-134-136-17.eu-west-2.compute.amazonaws.com"
env.K8S_CLuster_user="ubuntu@ec2-3-9-181-254.eu-west-2.compute.amazonaws.com"

// host key generated for ssh into vms
env.EC2_private_key="AWS_EU_Key"
